/*
 * The purpose of this program is to control an SG90 servo motor using PWM.
 * The PWM output signal is generated by CCP2/PWM2 and sent to RB3/D8.
 * Two pushbuttons are used to control the servo direction.
 *
 * When the left button is pressed, the PWM pulse width is slowly decreased,
 * causing the servo to move toward the left limit.
 *
 * When the right button is pressed, the PWM pulse width is slowly increased,
 * causing the servo to move toward the right limit.
 *
 * When both buttons are released, the pulse width stays the same, so the
 * servo stops moving and holds its current position.
 *
 * Timer2 is used as the PWM time base.
 *
 * PWM Period =
 * [T2PR + 1] * 4 * Tosc * Prescale
 *
 * For this program:
 * T2PR = 155
 * Prescale = 1:128
 * Fosc = 4 MHz
 * Tosc = 1 / Fosc
 *
 * PWM Period ≈ 20 ms, which is required for standard servo control.
 *
 * Pulse Width =
 * Tosc * Prescale * CCPR2
 *
 * The servo is controlled by changing the CCPR2 duty value:
 * Left limit   ≈ 0.5 ms pulse
 * Center       ≈ 1.5 ms pulse
 * Right limit  ≈ 2.5 ms pulse
 *
 * Author: Duy Pham
 */


#include <xc.h>
#include <stdint.h>
#include "PWM.h"

#define _XTAL_FREQ 4000000UL

// Buttons
// Assumption:
// Left button  = RB0
// Right button = RB1
// Buttons are active LOW using pull-up resistors
#define RIGHT_BUTTON     PORTBbits.RB0
#define LEFT_BUTTON    PORTBbits.RB1

#define PRESSED         0
#define RELEASED        1

// Servo duty values for your PWM.h Timer2 settings
// FOSC = 4 MHz
// T2PR = 155
// Timer2 prescaler = 1:128
// PWM period ≈ 20 ms
#define SERVO_LEFT_LIMIT     16      // about 0.5 ms pulse
#define SERVO_CENTER         46      // about 1.5 ms pulse
#define SERVO_RIGHT_LIMIT    76      // about 2.5 ms pulse

// Larger value = slower servo movement
#define SERVO_STEP_DELAY_MS  50

uint16_t servoDuty = SERVO_CENTER;

void OSCILLATOR_Initialize(void)
{
    // HFINTOSC selected, divider 1
    // This is for PIC18F47K42-style oscillator setup
    OSCCON1 = 0x60;

    // 4 MHz HFINTOSC
    OSCFRQ = 0x02;
}

void IO_Initialize(void)
{
    // -------------------------
    // Servo PWM output on RB3
    // -------------------------
    ANSELBbits.ANSELB3 = 0;      // RB3 digital
    TRISBbits.TRISB3 = 0;        // RB3 output
    LATBbits.LATB3 = 0;

    // -------------------------
    // Left button on RB0
    // -------------------------
    ANSELBbits.ANSELB0 = 0;      // RB0 digital
    TRISBbits.TRISB0 = 1;        // RB0 input
    WPUBbits.WPUB0 = 1;          // enable weak pull-up

    // -------------------------
    // Right button on RB1
    // -------------------------
    ANSELBbits.ANSELB1 = 0;      // RB1 digital
    TRISBbits.TRISB1 = 1;        // RB1 input
    WPUBbits.WPUB1 = 1;          // enable weak pull-up
}

void Servo_SetPosition(uint16_t duty)
{
    if (duty < SERVO_LEFT_LIMIT)
    {
        duty = SERVO_LEFT_LIMIT;
    }

    if (duty > SERVO_RIGHT_LIMIT)
    {
        duty = SERVO_RIGHT_LIMIT;
    }

    servoDuty = duty;

    // This function comes from your PWM.h file
    PWM2_LoadDutyValue(servoDuty);
}

void main(void)
{
    OSCILLATOR_Initialize();
    IO_Initialize();

    // Connect CCP2/PWM2 output to RB3/D8
    PWM_Output_D8_Enable();

    // Initialize CCP2 PWM module
    PWM2_Initialize();

    // Set center duty BEFORE starting Timer2
    // This avoids starting with the default value in PWM.h
    Servo_SetPosition(SERVO_CENTER);

    // Initialize and start Timer2
    TMR2_Initialize();

    while (1)
    {
        // Move left only while left button is pressed
        if ((LEFT_BUTTON == PRESSED) && (RIGHT_BUTTON == RELEASED))
        {
            if (servoDuty > SERVO_LEFT_LIMIT)
            {
                servoDuty--;
                Servo_SetPosition(servoDuty);
            }
            __delay_ms(SERVO_STEP_DELAY_MS);
        }

        // Move right only while right button is pressed
        else if ((RIGHT_BUTTON == PRESSED) && (LEFT_BUTTON == RELEASED))
        {
            if (servoDuty < SERVO_RIGHT_LIMIT)
            {
                servoDuty++;
                Servo_SetPosition(servoDuty);
            }

            __delay_ms(SERVO_STEP_DELAY_MS);
        }

        // No button pressed, or both buttons pressed
        else
        {
            // Do not change servoDuty.
            // PWM continues running, so servo holds position.
            __delay_ms(5000);
        }
    }
}
